### PR TITLE
Fix for new @import statements being ignored

### PR DESCRIPTION
**Pull request by marsupialmouse**
Adding an @import statement in a .less file fails to update the list of imports for that file, which means that any subsequent change to the imported file(s) does not cause the .less file with @import statements to be recompiled. This fix changes the way the main watchStream works so that the callback is wrapped and the @imports of all changed files are compared.

There is an [open issue for this in the original gulp-watch-less](https://github.com/Craga89/gulp-watch-less/issues/7).

### CODE REVIEW

**Comment by giiska** [comment]
I tried on both gulp 3.9.0 and gulp 4, there was no problem.

The following changes will trigger the .less file to recompile and get the result as expect.
- Add new @import statement(s) to .less file
- Change less code in the imported file
- Reorder the @import list in the .less file
- Delete @import statement(s) in the .less file
- Change less code in the .less file

**Comment by marsupialmouse** [comment]
The problem only seems to manifest itself when a new .less file is involved. For example, if you add a new file and then add @import statements to an existing .less file to import the new file:
1. Add a new .less file.
2. Add an @import statement to an existing .less file to import the new file.
3. Change less code in the new .less file.

In the third step both the new and existing .less files should be compiled, but only the new .less file is compiled.

Additionally, adding @import statements to new files doesn't work as it should:
1. Add a new .less file.
2. Add an @import statement to the new file to import an existing .less file.
3. Change less code in the existing .less file.

In the third step both the new and existing .less files should be compiled, but only the existing .less file is compiled.

I'm using gulp 3.9.0.

**Comment by giiska** [comment]
@marsupialmouse  Can you show your gulp task code? And which Gulp Cli version do you use?

**Comment by marsupialmouse** [comment]
The CLI is also 3.9.0. Here's the task:

```
gulp.task('less-watch', function () {
    return gulp
         .src('content/less/**/*.less')
         .pipe(watchLess('content/less/**/*.less', { verbose: true }))
         .pipe(less())
         .pipe(gulp.dest('content/css'));
});
```

I have some .less files directly in content/less that import files from sub directories and some in subdirectories that import .less files from other subdirectories.

**Comment by giiska** [comment]
Ok, you mix the main less files and import files. You won't get any benefit by using this plugin as it watches all less files.

You should use a filter in you gulp src like this:

``` javascript
var lessGlobs = ['content/less/main-*', 'content/less/**/main-*'];
gulp.task('less-watch', function () {
  return gulp.src(lessGlobs)
        .pipe(watchLess(lessGlobs, {verbose: true}))
        .pipe(less())
        .pipe(gulp.dest('content/css'));
});
```

Only files start with prefix `main-` will be compiled and watched.

It should also work fine to use negative filter like `gulp.src(['content/less/**/*.less', '!content/less/_*.less'])` when import file name are begin with `_`.

**Comment by marsupialmouse** [comment]
Thanks - using a more specific glob fixes the problem of importing new files. Unfortunately it also uncovers some other problems. 

Let's say I have this directory structure:

```
content/less/desktop.less                   (imports about.less and home.less)
content/less/desktop/includes/colours.less  (contains colour variables)
content/less/desktop/pages/about.less       (just styles, no imports)
content/less/desktop/pages/home.less        (just styles, no imports)
content/less/desktop/pages/search.less      (styles + import colours.less)
```

We only need to compile the .less files in the base content/less directory, so we use this task:

```
gulp.task('less-watch', function () {
    return gulp
         .src(['content/less/*.less'])
         .pipe(watchLess('content/less/*.less', { verbose: true, base: 'content/less' }))
         .pipe(less())
         .pipe(gulp.dest('content/css'));
});
```
- Change home.less to import colours.less (recompiles desktop.less - **right**)
- Change variable in colours.less (does nothing - **wrong**: should recompile desktop.less)
- Remove import statement from home.less (recompiles desktop.less - **right**)
- Change variable in colours.less (does nothing - **right**)
- Change desktop.less to import search.less (recompiles desktop.less - **right**)
- Change variable in colours.less (recompiles desktop.less - **right**)
- Remove import statement from search.less (recompiles desktop.less - **right**)
- Change variable in colours.less (recompiles desktop.less - **wrong**: colours.less is no longer imported by any .less files)
- Delete desktop.less (error on line 23 of index.js - process terminated - **wrong**)

Renaming desktop.less (instead of deleting it) results in the same error.

It looks like my pull request doesn't work properly with the simplified glob anyway, so I'll close this.

**Comment by giiska** [comment]
@marsupialmouse Thank you for testing it so detailed, can you move this to a new issue? I will fix these in the next version.

**Comment by marsupialmouse** [comment]
Thanks, will do.

**Pull request closed without merging**
